# -*- coding: utf-8 -*-

"""
***********************************
tests.test_utility_functions.py
***********************************

Tests for the functions contained in :module:`utility_functions.py <utility_functions>`.

"""
import pytest

from validator_collection._compat import basestring
from validator_collection import checkers

from open_api.utility_functions import validate_url, traverse_dict, \
    validate_runtime_expression, validate_component_map_key, validate_mimetype


@pytest.mark.parametrize('value, fails, allow_empty, allow_special_ips', [
    (u"http://foo.com/blah_blah", False, False, False),
    (u"http://foo.com/blah_blah/", False, False, False),
    (u"http://foo.com/blah_blah_(wikipedia)", False, False, False),
    (u"http://foo.com/blah_blah_(wikipedia)_(again)", False, False, False),
    (u"http://www.example.com/wpstyle/?p=364", False, False, False),
    (u"https://www.example.com/foo/?bar=baz&inga=42&quux", False, False, False),
    (u"http://✪df.ws/123", False, False, False),
    (u"http://userid:password@example.com:8080", False, False, False),
    (u"http://userid:password@example.com:8080/", False, False, False),
    (u"http://userid@example.com", False, False, False),
    (u"http://userid@example.com/", False, False, False),
    (u"http://userid@example.com:8080", False, False, False),
    (u"http://userid@example.com:8080/", False, False, False),
    (u"http://userid:password@example.com", False, False, False),
    (u"http://userid:password@example.com/", False, False, False),
    (u"http://142.42.1.1/", False, False, False),
    (u"http://142.42.1.1:8080/", False, False, False),
    (u"http://➡.ws/䨹", False, False, False),
    (u"http://⌘.ws", False, False, False),
    (u"http://⌘.ws/", False, False, False),
    (u"http://foo.com/blah_(wikipedia)#cite-1", False, False, False),
    (u"http://foo.com/blah_(wikipedia)_blah#cite-1", False, False, False),
    (u"http://foo.com/unicode_(✪)_in_parens", False, False, False),
    (u"http://foo.com/(something)?after=parens", False, False, False),
    (u"http://☺.damowmow.com/", False, False, False),
    (u"http://jurnalsda_pusair.pu.go.id", False, False, False),
    (u"http://code.google.com/events/#&product=browser", False, False, False),
    (u"http://j.mp", False, False, False),
    (u"ftp://foo.bar/baz", False, False, False),
    (u"http://foo.bar/?q=Test%20URL-encoded%20stuff", False, False, False),
    (u"http://مثال.إختبار", False, False, False),
    (u"http://例子.测试", False, False, False),
    (u"http://उदाहरण.परीक्षा", False, False, False),
    (u"http://-.~_!$&'()*+,;=:%40:80%2f::::::@example.com", False, False, False),
    (u"http://1337.net", False, False, False),
    (u"http://a.b-c.de", False, False, False),
    (u"http://a.b--c.de/", False, False, False),
    (u"http://223.255.255.254", False, False, False),
    (u"", True, False, False),
    (None, True, False, False),
    (u"http://", True, False, False),
    (u"http://.", True, False, False),
    (u"http://..", True, False, False),
    (u"http://../", True, False, False),
    (u"http://?", True, False, False),
    (u"http://??", True, False, False),
    (u"http://??/", True, False, False),
    (u"http://#", True, False, False),
    (u"http://##", True, False, False),
    (u"http://##/", True, False, False),
    (u"http://foo.bar?q=Spaces should be encoded", True, False, False),
    (u"//", False, False, False),
    (u"//a", False, False, False),
    (u"///a", False, False, False),
    (u"///", False, False, False),
    (u"http:///a", True, False, False),
    (u"foo.com", False, False, False),
    (u"rdar://1234", True, False, False),
    (u"h://test", True, False, False),
    (u"http:// shouldfail.com", True, False, False),
    (u":// should fail", True, False, False),
    (u"http://foo.bar/foo(bar)baz quux", True, False, False),
    (u"ftps://foo.bar/", True, False, False),
    (u"http://-error-.invalid/", True, False, False),
    (u"http://-a.b.co", True, False, False),
    (u"http://a.b-.co", True, False, False),
    (u"http://0.0.0.0", True, False, False),
    (u"http://10.1.1.0", True, False, False),
    (u"http://10.1.1.255", True, False, False),
    (u"http://224.1.1.1", True, False, False),
    (u"http://1.1.1.1.1", True, False, False),
    (u"http://123.123.123", True, False, False),
    (u"http://3628126748", True, False, False),
    (u"http://.www.foo.bar/", True, False, False),
    (u"http://www.foo.bar./", True, False, False),
    (u"http://.www.foo.bar./", True, False, False),
    (u"http://10.1.1.1", True, False, False),
    (u"", False, True, False),
    (None, False, True, False),

    (u"localhost", False, False, False),
    (u"abc.localhost.com", False, False, False),
    (u"invalid", False, False, False),
    (u"abc.invalid.com", False, False, False),

    (u"http://localhost", False, False, False),
    (u"http://abc.localhost.com", False, False, False),
    (u"http://invalid", False, False, False),
    (u"http://abc.invalid.com", False, False, False),

    (u"http://foo.com/blah_blah", False, False, True),
    (u"http://foo.com/blah_blah/", False, False, True),
    (u"http://foo.com/blah_blah_(wikipedia)", False, False, True),
    (u"http://foo.com/blah_blah_(wikipedia)_(again)", False, False, True),
    (u"http://www.example.com/wpstyle/?p=364", False, False, True),
    (u"https://www.example.com/foo/?bar=baz&inga=42&quux", False, False, True),
    (u"http://✪df.ws/123", False, False, True),
    (u"http://userid:password@example.com:8080", False, False, True),
    (u"http://userid:password@example.com:8080/", False, False, True),
    (u"http://userid@example.com", False, False, True),
    (u"http://userid@example.com/", False, False, True),
    (u"http://userid@example.com:8080", False, False, True),
    (u"http://userid@example.com:8080/", False, False, True),
    (u"http://userid:password@example.com", False, False, True),
    (u"http://userid:password@example.com/", False, False, True),
    (u"http://142.42.1.1/", False, False, True),
    (u"http://142.42.1.1:8080/", False, False, True),
    (u"http://➡.ws/䨹", False, False, True),
    (u"http://⌘.ws", False, False, True),
    (u"http://⌘.ws/", False, False, True),
    (u"http://foo.com/blah_(wikipedia)#cite-1", False, False, True),
    (u"http://foo.com/blah_(wikipedia)_blah#cite-1", False, False, True),
    (u"http://foo.com/unicode_(✪)_in_parens", False, False, True),
    (u"http://foo.com/(something)?after=parens", False, False, True),
    (u"http://☺.damowmow.com/", False, False, True),
    (u"http://jurnalsda_pusair.pu.go.id", False, False, True),
    (u"http://code.google.com/events/#&product=browser", False, False, True),
    (u"http://j.mp", False, False, True),
    (u"ftp://foo.bar/baz", False, False, True),
    (u"http://foo.bar/?q=Test%20URL-encoded%20stuff", False, False, True),
    (u"http://مثال.إختبار", False, False, True),
    (u"http://例子.测试", False, False, True),
    (u"http://उदाहरण.परीक्षा", False, False, True),
    (u"http://-.~_!$&'()*+,;=:%40:80%2f::::::@example.com", False, False, True),
    (u"http://1337.net", False, False, True),
    (u"http://a.b-c.de", False, False, True),
    (u"http://a.b--c.de/", False, False, True),
    (u"http://223.255.255.254", False, False, True),
    (u"", True, False, True),
    (None, True, False, True),
    (u"http://", True, False, True),
    (u"http://.", True, False, True),
    (u"http://..", True, False, True),
    (u"http://../", True, False, True),
    (u"http://?", True, False, True),
    (u"http://??", True, False, True),
    (u"http://??/", True, False, True),
    (u"http://#", True, False, True),
    (u"http://##", True, False, True),
    (u"http://##/", True, False, True),
    (u"http://foo.bar?q=Spaces should be encoded", True, False, True),
    (u"//", False, False, True),
    (u"//a", False, False, True),
    (u"///a", False, False, True),
    (u"///", False, False, True),
    (u"http:///a", True, False, True),
    (u"foo.com", False, False, True),
    (u"rdar://1234", True, False, True),
    (u"h://test", True, False, True),
    (u"http:// shouldfail.com", True, False, True),
    (u":// should fail", True, False, True),
    (u"http://foo.bar/foo(bar)baz quux", True, False, True),
    (u"ftps://foo.bar/", True, False, True),
    (u"http://-error-.invalid/", True, False, True),
    (u"http://-a.b.co", True, False, True),
    (u"http://a.b-.co", True, False, True),
    (u"http://0.0.0.0", False, False, True),
    (u"http://10.1.1.0", False, False, True),
    (u"http://10.1.1.255", False, False, True),
    (u"http://224.1.1.1", False, False, True),
    (u"http://1.1.1.1.1", True, False, True),
    (u"http://123.123.123", True, False, True),
    (u"http://3628126748", True, False, True),
    (u"http://.www.foo.bar/", True, False, True),
    (u"http://www.foo.bar./", True, False, True),
    (u"http://.www.foo.bar./", True, False, True),
    (u"http://10.1.1.1", False, False, True),
    (u"", False, True, True),
    (None, False, True, True),

    (u"localhost", False, False, True),
    (u"abc.localhost.com", False, False, True),
    (u"invalid", False, False, True),
    (u"abc.invalid.com", False, False, True),

    (u"http://localhost", False, False, True),
    (u"http://abc.localhost.com", False, False, True),
    (u"http://invalid", False, False, True),
    (u"http://abc.invalid.com", False, False, True),


    (u"https://{somevariable}.testurl.com/api", False, False, True),
    (u"/{someVariable}testpath.com/{other_Variable}/{other}", False, False, True),
    (u"https://{username}.gigantic-server.com:{port}/{basePath}", False, False, True),
])
def test_validate_url(value, fails, allow_empty, allow_special_ips):
    """Test the URL validator."""
    if not fails:
        validated = validate_url(value,
                                 allow_empty = allow_empty,
                                 allow_special_ips = allow_special_ips)
        if value:
            assert isinstance(validated, basestring)
        else:
            assert validated is None
    else:
        with pytest.raises((ValueError, TypeError)):
            value = validate_url(value, allow_empty = allow_empty)


@pytest.mark.parametrize('content, target, expects, error', [
    ({'test': 'value', 'test2': {'something': 'value', 'something2': {'level3': 123}}}, 'test', ['test'], None),
    ({'test': 'value', 'test2': {'something': 'value', 'something2': {'level3': 123}}}, 'test2', ['test2'], None),
    ({'test': 'value', 'test2': {'something': 'value', 'something2': {'level3': 123}}}, 'something', ['test2', 'something'], None),
    ({'test': 'value', 'test2': {'something': 'value', 'something2': {'level3': 123}}}, 'level3', ['test2', 'something2', 'level3'], None),

    ({'test': 'value', 'test2': {'something': 'value', 'something2': {'level3': 123}}}, 'missing-value', [], None),
])
def test_traverse_dict(content, target, expects, error):
    if not error:
        result = traverse_dict(content, target)
        assert len(result) == len(expects)
        assert checkers.are_equivalent(expects, result)
    else:
        with pytest.raises(error):
            result = traverse_dict(content, target)


@pytest.mark.parametrize('value, fails, allow_empty', [
    ('$method', False, False),
    ('$request.header.accept', False, False),
    ('$request.path.id', False, False),
    ('$request.body#/user/uuid', False, False),
    ('$url', False, False),
    ('$response.body#/status', False, False),
    ('$response.header.Server', False, False),

    ('invalid expression', True, False),
])
def test_validate_runtime_expression(value, fails, allow_empty):
    if not fails:
        validated = validate_runtime_expression(value, allow_empty = allow_empty)
        if value:
            assert validated is not None
        else:
            assert validated is None
    else:
        with pytest.raises(ValueError):
            value = validate_runtime_expression(value, allow_empty = allow_empty)


@pytest.mark.parametrize('value, fails, allow_empty', [
    ('User', False, False),
    ('User_1', False, False),
    ('User_Name', False, False),
    ('user-name', False, False),
    ('my.org.User', False, False),

    ('invalid expression', True, False),
])
def test_validate_component_map_key(value, fails, allow_empty):
    if not fails:
        validated = validate_component_map_key(value, allow_empty = allow_empty)
        if value:
            assert validated is not None
        else:
            assert validated is None
    else:
        with pytest.raises(ValueError):
            value = validate_component_map_key(value, allow_empty = allow_empty)


@pytest.mark.parametrize('value, fails, allow_empty', [
    ('application/vnd.hzn-3d-crossword', False, False),
    ('video/3gpp', False, False),
    ('video/3gpp2', False, False),
    ('application/vnd.mseq', False, False),
    ('application/vnd.3m.post-it-notes', False, False),
    ('application/vnd.3gpp.pic-bw-large', False, False),
    ('application/vnd.3gpp.pic-bw-small', False, False),
    ('application/vnd.3gpp.pic-bw-var', False, False),
    ('application/vnd.3gpp2.tcap', False, False),
    ('application/x-7z-compressed', False, False),
    ('application/x-abiword', False, False),
    ('application/x-ace-compressed', False, False),
    ('application/vnd.americandynamics.acc', False, False),
    ('application/vnd.acucobol', False, False),
    ('application/vnd.acucorp', False, False),
    ('audio/adpcm', False, False),
    ('application/x-authorware-bin', False, False),
    ('application/x-authorware-map', False, False),
    ('application/x-authorware-seg', False, False),
    ('application/x-shockwave-flash', False, False),
    ('application/vnd.adobe.fxp', False, False),
    ('application/pdf', False, False),
    ('application/vnd.cups-ppd', False, False),
    ('application/x-director', False, False),
    ('application/vnd.adobe.xfdf', False, False),
    ('audio/x-aac', False, False),
    ('application/vnd.ahead.space', False, False),
    ('application/vnd.airzip.filesecure.azf', False, False),
    ('application/vnd.airzip.filesecure.azs', False, False),
    ('application/vnd.amazon.ebook', False, False),
    ('application/vnd.amiga.ami', False, False),
    ('application/andrew-inset', False, False),
    ('application/vnd.android.package-archive', False, False),
    ('application/vnd.anser-web-certificate-issue-initiation', False, False),
    ('application/vnd.anser-web-funds-transfer-initiation', False, False),
    ('application/vnd.antix.game-component', False, False),
    ('application/x-apple-diskimage', False, False),
    ('application/vnd.apple.installer+xml', False, False),
    ('application/applixware', False, False),
    ('application/vnd.hhe.lesson-player', False, False),
    ('application/vnd.aristanetworks.swi', False, False),
    ('text/x-asm', False, False),
    ('application/atomcat+xml', False, False),
    ('application/atomsvc+xml', False, False),
    ('application/atom+xml', False, False),
    ('application/pkix-attr-cert', False, False),
    ('audio/x-aiff', False, False),
    ('video/x-msvideo', False, False),
    ('application/vnd.audiograph', False, False),
    ('image/vnd.dxf', False, False),
    ('model/vnd.dwf', False, False),
    ('text/plain-bas', False, False),
    ('application/x-bcpio', False, False),
    ('application/octet-stream', False, False),
    ('image/bmp', False, False),
    ('application/x-bittorrent', False, False),
    ('application/vnd.rim.cod', False, False),
    ('application/vnd.blueice.multipass', False, False),
    ('application/vnd.bmi', False, False),
    ('application/x-sh', False, False),
    ('image/prs.btif', False, False),
    ('application/vnd.businessobjects', False, False),
    ('application/x-bzip', False, False),
    ('application/x-bzip2', False, False),
    ('application/x-csh', False, False),
    ('text/x-c', False, False),
    ('application/vnd.chemdraw+xml', False, False),
    ('text/css', False, False),
    ('chemical/x-cdx', False, False),
    ('chemical/x-cml', False, False),
    ('chemical/x-csml', False, False),
    ('application/vnd.contact.cmsg', False, False),
    ('application/vnd.claymore', False, False),
    ('application/vnd.clonk.c4group', False, False),
    ('image/vnd.dvb.subtitle', False, False),
    ('application/cdmi-capability', False, False),
    ('application/cdmi-container', False, False),
    ('application/cdmi-domain', False, False),
    ('application/cdmi-object', False, False),
    ('application/cdmi-queue', False, False),
    ('application/vnd.cluetrust.cartomobile-config', False, False),
    ('application/vnd.cluetrust.cartomobile-config-pkg', False, False),
    ('image/x-cmu-raster', False, False),
    ('model/vnd.collada+xml', False, False),
    ('text/csv', False, False),
    ('application/mac-compactpro', False, False),
    ('application/vnd.wap.wmlc', False, False),
    ('image/cgm', False, False),
    ('x-conference/x-cooltalk', False, False),
    ('image/x-cmx', False, False),
    ('application/vnd.xara', False, False),
    ('application/vnd.cosmocaller', False, False),
    ('application/x-cpio', False, False),
    ('application/vnd.crick.clicker', False, False),
    ('application/vnd.crick.clicker.keyboard', False, False),
    ('application/vnd.crick.clicker.palette', False, False),
    ('application/vnd.crick.clicker.template', False, False),
    ('application/vnd.crick.clicker.wordbank', False, False),
    ('application/vnd.criticaltools.wbs+xml', False, False),
    ('application/vnd.rig.cryptonote', False, False),
    ('chemical/x-cif', False, False),
    ('chemical/x-cmdf', False, False),
    ('application/cu-seeme', False, False),
    ('application/prs.cww', False, False),
    ('text/vnd.curl', False, False),
    ('text/vnd.curl.dcurl', False, False),
    ('text/vnd.curl.mcurl', False, False),
    ('text/vnd.curl.scurl', False, False),
    ('application/vnd.curl.car', False, False),
    ('application/vnd.curl.pcurl', False, False),
    ('application/vnd.yellowriver-custom-menu', False, False),
    ('application/dssc+der', False, False),
    ('application/dssc+xml', False, False),
    ('application/x-debian-package', False, False),
    ('audio/vnd.dece.audio', False, False),
    ('image/vnd.dece.graphic', False, False),
    ('video/vnd.dece.hd', False, False),
    ('video/vnd.dece.mobile', False, False),
    ('video/vnd.uvvu.mp4', False, False),
    ('video/vnd.dece.pd', False, False),
    ('video/vnd.dece.sd', False, False),
    ('video/vnd.dece.video', False, False),
    ('application/x-dvi', False, False),
    ('application/vnd.fdsn.seed', False, False),
    ('application/x-dtbook+xml', False, False),
    ('application/x-dtbresource+xml', False, False),
    ('application/vnd.dvb.ait', False, False),
    ('application/vnd.dvb.service', False, False),
    ('audio/vnd.digital-winds', False, False),
    ('image/vnd.djvu', False, False),
    ('application/xml-dtd', False, False),
    ('application/vnd.dolby.mlp', False, False),
    ('application/x-doom', False, False),
    ('application/vnd.dpgraph', False, False),
    ('audio/vnd.dra', False, False),
    ('application/vnd.dreamfactory', False, False),
    ('audio/vnd.dts', False, False),
    ('audio/vnd.dts.hd', False, False),
    ('image/vnd.dwg', False, False),
    ('application/vnd.dynageo', False, False),
    ('application/ecmascript', False, False),
    ('application/vnd.ecowin.chart', False, False),
    ('image/vnd.fujixerox.edmics-mmr', False, False),
    ('image/vnd.fujixerox.edmics-rlc', False, False),
    ('application/exi', False, False),
    ('application/vnd.proteus.magazine', False, False),
    ('application/epub+zip', False, False),
    ('message/rfc822', False, False),
    ('application/vnd.enliven', False, False),
    ('application/vnd.is-xpr', False, False),
    ('image/vnd.xiff', False, False),
    ('application/vnd.xfdl', False, False),
    ('application/emma+xml', False, False),
    ('application/vnd.ezpix-album', False, False),
    ('application/vnd.ezpix-package', False, False),
    ('image/vnd.fst', False, False),
    ('video/vnd.fvt', False, False),
    ('image/vnd.fastbidsheet', False, False),
    ('application/vnd.denovo.fcselayout-link', False, False),
    ('video/x-f4v', False, False),
    ('video/x-flv', False, False),
    ('image/vnd.fpx', False, False),
    ('image/vnd.net-fpx', False, False),
    ('text/vnd.fmi.flexstor', False, False),
    ('video/x-fli', False, False),
    ('application/vnd.fluxtime.clip', False, False),
    ('application/vnd.fdf', False, False),
    ('text/x-fortran', False, False),
    ('application/vnd.mif', False, False),
    ('application/vnd.framemaker', False, False),
    ('image/x-freehand', False, False),
    ('application/vnd.fsc.weblaunch', False, False),
    ('application/vnd.frogans.fnc', False, False),
    ('application/vnd.frogans.ltf', False, False),
    ('application/vnd.fujixerox.ddd', False, False),
    ('application/vnd.fujixerox.docuworks', False, False),
    ('application/vnd.fujixerox.docuworks.binder', False, False),
    ('application/vnd.fujitsu.oasys', False, False),
    ('application/vnd.fujitsu.oasys2', False, False),
    ('application/vnd.fujitsu.oasys3', False, False),
    ('application/vnd.fujitsu.oasysgp', False, False),
    ('application/vnd.fujitsu.oasysprs', False, False),
    ('application/x-futuresplash', False, False),
    ('application/vnd.fuzzysheet', False, False),
    ('image/g3fax', False, False),
    ('application/vnd.gmx', False, False),
    ('model/vnd.gtw', False, False),
    ('application/vnd.genomatix.tuxedo', False, False),
    ('application/vnd.geogebra.file', False, False),
    ('application/vnd.geogebra.tool', False, False),
    ('model/vnd.gdl', False, False),
    ('application/vnd.geometry-explorer', False, False),
    ('application/vnd.geonext', False, False),
    ('application/vnd.geoplan', False, False),
    ('application/vnd.geospace', False, False),
    ('application/x-font-ghostscript', False, False),
    ('application/x-font-bdf', False, False),
    ('application/x-gtar', False, False),
    ('application/x-texinfo', False, False),
    ('application/x-gnumeric', False, False),
    ('application/vnd.google-earth.kml+xml', False, False),
    ('application/vnd.google-earth.kmz', False, False),
    ('application/vnd.grafeq', False, False),
    ('image/gif', False, False),
    ('text/vnd.graphviz', False, False),
    ('application/vnd.groove-account', False, False),
    ('application/vnd.groove-help', False, False),
    ('application/vnd.groove-identity-message', False, False),
    ('application/vnd.groove-injector', False, False),
    ('application/vnd.groove-tool-message', False, False),
    ('application/vnd.groove-tool-template', False, False),
    ('application/vnd.groove-vcard', False, False),
    ('video/h261', False, False),
    ('video/h263', False, False),
    ('video/h264', False, False),
    ('application/vnd.hp-hpid', False, False),
    ('application/vnd.hp-hps', False, False),
    ('application/x-hdf', False, False),
    ('audio/vnd.rip', False, False),
    ('application/vnd.hbci', False, False),
    ('application/vnd.hp-jlyt', False, False),
    ('application/vnd.hp-pcl', False, False),
    ('application/vnd.hp-hpgl', False, False),
    ('application/vnd.yamaha.hv-script', False, False),
    ('application/vnd.yamaha.hv-dic', False, False),
    ('application/vnd.yamaha.hv-voice', False, False),
    ('application/vnd.hydrostatix.sof-data', False, False),
    ('application/hyperstudio', False, False),
    ('application/vnd.hal+xml', False, False),
    ('text/html', False, False),
    ('application/vnd.ibm.rights-management', False, False),
    ('application/vnd.ibm.secure-container', False, False),
    ('text/calendar', False, False),
    ('application/vnd.iccprofile', False, False),
    ('image/x-icon', False, False),
    ('application/vnd.igloader', False, False),
    ('image/ief', False, False),
    ('application/vnd.immervision-ivp', False, False),
    ('application/vnd.immervision-ivu', False, False),
    ('application/reginfo+xml', False, False),
    ('text/vnd.in3d.3dml', False, False),
    ('text/vnd.in3d.spot', False, False),
    ('model/iges', False, False),
    ('application/vnd.intergeo', False, False),
    ('application/vnd.cinderella', False, False),
    ('application/vnd.intercon.formnet', False, False),
    ('application/vnd.isac.fcs', False, False),
    ('application/ipfix', False, False),
    ('application/pkix-cert', False, False),
    ('application/pkixcmp', False, False),
    ('application/pkix-crl', False, False),
    ('application/pkix-pkipath', False, False),
    ('application/vnd.insors.igm', False, False),
    ('application/vnd.ipunplugged.rcprofile', False, False),
    ('application/vnd.irepository.package+xml', False, False),
    ('text/vnd.sun.j2me.app-descriptor', False, False),
    ('application/java-archive', False, False),
    ('application/java-vm', False, False),
    ('application/x-java-jnlp-file', False, False),
    ('application/java-serialized-object', False, False),
    ('text/x-java-source,java', True, False),
    ('application/javascript', False, False),
    ('application/json', False, False),
    ('application/vnd.joost.joda-archive', False, False),
    ('video/jpm', False, False),
    ('image/jpeg', False, False),
    ('image/x-citrix-jpeg', False, False),
    ('image/pjpeg', False, False),
    ('video/jpeg', False, False),
    ('application/vnd.kahootz', False, False),
    ('application/vnd.chipnuts.karaoke-mmd', False, False),
    ('application/vnd.kde.karbon', False, False),
    ('application/vnd.kde.kchart', False, False),
    ('application/vnd.kde.kformula', False, False),
    ('application/vnd.kde.kivio', False, False),
    ('application/vnd.kde.kontour', False, False),
    ('application/vnd.kde.kpresenter', False, False),
    ('application/vnd.kde.kspread', False, False),
    ('application/vnd.kde.kword', False, False),
    ('application/vnd.kenameaapp', False, False),
    ('application/vnd.kidspiration', False, False),
    ('application/vnd.kinar', False, False),
    ('application/vnd.kodak-descriptor', False, False),
    ('application/vnd.las.las+xml', False, False),
    ('application/x-latex', False, False),
    ('application/vnd.llamagraphics.life-balance.desktop', False, False),
    ('application/vnd.llamagraphics.life-balance.exchange+xml', False, False),
    ('application/vnd.jam', False, False),
    ('application/vnd.lotus-1-2-3', False, False),
    ('application/vnd.lotus-approach', False, False),
    ('application/vnd.lotus-freelance', False, False),
    ('application/vnd.lotus-notes', False, False),
    ('application/vnd.lotus-organizer', False, False),
    ('application/vnd.lotus-screencam', False, False),
    ('application/vnd.lotus-wordpro', False, False),
    ('audio/vnd.lucent.voice', False, False),
    ('audio/x-mpegurl', False, False),
    ('video/x-m4v', False, False),
    ('application/mac-binhex40', False, False),
    ('application/vnd.macports.portpkg', False, False),
    ('application/vnd.osgeo.mapguide.package', False, False),
    ('application/marc', False, False),
    ('application/marcxml+xml', False, False),
    ('application/mxf', False, False),
    ('application/vnd.wolfram.player', False, False),
    ('application/mathematica', False, False),
    ('application/mathml+xml', False, False),
    ('application/mbox', False, False),
    ('application/vnd.medcalcdata', False, False),
    ('application/mediaservercontrol+xml', False, False),
    ('application/vnd.mediastation.cdkey', False, False),
    ('application/vnd.mfer', False, False),
    ('application/vnd.mfmp', False, False),
    ('model/mesh', False, False),
    ('application/mads+xml', False, False),
    ('application/mets+xml', False, False),
    ('application/mods+xml', False, False),
    ('application/metalink4+xml', False, False),
    ('application/vnd.mcd', False, False),
    ('application/vnd.micrografx.flo', False, False),
    ('application/vnd.micrografx.igx', False, False),
    ('application/vnd.eszigno3+xml', False, False),
    ('application/x-msaccess', False, False),
    ('video/x-ms-asf', False, False),
    ('application/x-msdownload', False, False),
    ('application/vnd.ms-artgalry', False, False),
    ('application/vnd.ms-cab-compressed', False, False),
    ('application/vnd.ms-ims', False, False),
    ('application/x-ms-application', False, False),
    ('application/x-msclip', False, False),
    ('image/vnd.ms-modi', False, False),
    ('application/vnd.ms-fontobject', False, False),
    ('application/vnd.ms-excel', False, False),
    ('application/vnd.ms-excel.addin.macroenabled.12', False, False),
    ('application/vnd.ms-excel.sheet.binary.macroenabled.12', False, False),
    ('application/vnd.ms-excel.template.macroenabled.12', False, False),
    ('application/vnd.ms-excel.sheet.macroenabled.12', False, False),
    ('application/vnd.ms-htmlhelp', False, False),
    ('application/x-mscardfile', False, False),
    ('application/vnd.ms-lrm', False, False),
    ('application/x-msmediaview', False, False),
    ('application/x-msmoney', False, False),
    ('application/vnd.openxmlformats-officedocument.presentationml.presentation', False, False),
    ('application/vnd.openxmlformats-officedocument.presentationml.slide', False, False),
    ('application/vnd.openxmlformats-officedocument.presentationml.slideshow', False, False),
    ('application/vnd.openxmlformats-officedocument.presentationml.template', False, False),
    ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', False, False),
    ('application/vnd.openxmlformats-officedocument.spreadsheetml.template', False, False),
    ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', False, False),
    ('application/vnd.openxmlformats-officedocument.wordprocessingml.template', False, False),
    ('application/x-msbinder', False, False),
    ('application/vnd.ms-officetheme', False, False),
    ('application/onenote', False, False),
    ('audio/vnd.ms-playready.media.pya', False, False),
    ('video/vnd.ms-playready.media.pyv', False, False),
    ('application/vnd.ms-powerpoint', False, False),
    ('application/vnd.ms-powerpoint.addin.macroenabled.12', False, False),
    ('application/vnd.ms-powerpoint.slide.macroenabled.12', False, False),
    ('application/vnd.ms-powerpoint.presentation.macroenabled.12', False, False),
    ('application/vnd.ms-powerpoint.slideshow.macroenabled.12', False, False),
    ('application/vnd.ms-powerpoint.template.macroenabled.12', False, False),
    ('application/vnd.ms-project', False, False),
    ('application/x-mspublisher', False, False),
    ('application/x-msschedule', False, False),
    ('application/x-silverlight-app', False, False),
    ('application/vnd.ms-pki.stl', False, False),
    ('application/vnd.ms-pki.seccat', False, False),
    ('application/vnd.visio', False, False),
    ('application/vnd.visio2013', False, False),
    ('video/x-ms-wm', False, False),
    ('audio/x-ms-wma', False, False),
    ('audio/x-ms-wax', False, False),
    ('video/x-ms-wmx', False, False),
    ('application/x-ms-wmd', False, False),
    ('application/vnd.ms-wpl', False, False),
    ('application/x-ms-wmz', False, False),
    ('video/x-ms-wmv', False, False),
    ('video/x-ms-wvx', False, False),
    ('application/x-msmetafile', False, False),
    ('application/x-msterminal', False, False),
    ('application/msword', False, False),
    ('application/vnd.ms-word.document.macroenabled.12', False, False),
    ('application/vnd.ms-word.template.macroenabled.12', False, False),
    ('application/x-mswrite', False, False),
    ('application/vnd.ms-works', False, False),
    ('application/x-ms-xbap', False, False),
    ('application/vnd.ms-xpsdocument', False, False),
    ('audio/midi', False, False),
    ('application/vnd.ibm.minipay', False, False),
    ('application/vnd.ibm.modcap', False, False),
    ('application/vnd.jcp.javame.midlet-rms', False, False),
    ('application/vnd.tmobile-livetv', False, False),
    ('application/x-mobipocket-ebook', False, False),
    ('application/vnd.mobius.mbk', False, False),
    ('application/vnd.mobius.dis', False, False),
    ('application/vnd.mobius.plc', False, False),
    ('application/vnd.mobius.mqy', False, False),
    ('application/vnd.mobius.msl', False, False),
    ('application/vnd.mobius.txf', False, False),
    ('application/vnd.mobius.daf', False, False),
    ('text/vnd.fly', False, False),
    ('application/vnd.mophun.certificate', False, False),
    ('application/vnd.mophun.application', False, False),
    ('video/mj2', False, False),
    ('audio/mpeg', False, False),
    ('video/vnd.mpegurl', False, False),
    ('video/mpeg', False, False),
    ('application/mp21', False, False),
    ('audio/mp4', False, False),
    ('video/mp4', False, False),
    ('application/mp4', False, False),
    ('application/vnd.apple.mpegurl', False, False),
    ('application/vnd.musician', False, False),
    ('application/vnd.muvee.style', False, False),
    ('application/xv+xml', False, False),
    ('application/vnd.nokia.n-gage.data', False, False),
    ('application/vnd.nokia.n-gage.symbian.install', False, False),
    ('application/x-dtbncx+xml', False, False),
    ('application/x-netcdf', False, False),
    ('application/vnd.neurolanguage.nlu', False, False),
    ('application/vnd.dna', False, False),
    ('application/vnd.noblenet-directory', False, False),
    ('application/vnd.noblenet-sealer', False, False),
    ('application/vnd.noblenet-web', False, False),
    ('application/vnd.nokia.radio-preset', False, False),
    ('application/vnd.nokia.radio-presets', False, False),
    ('text/n3', False, False),
    ('application/vnd.novadigm.edm', False, False),
    ('application/vnd.novadigm.edx', False, False),
    ('application/vnd.novadigm.ext', False, False),
    ('application/vnd.flographit', False, False),
    ('audio/vnd.nuera.ecelp4800', False, False),
    ('audio/vnd.nuera.ecelp7470', False, False),
    ('audio/vnd.nuera.ecelp9600', False, False),
    ('application/oda', False, False),
    ('application/ogg', False, False),
    ('audio/ogg', False, False),
    ('video/ogg', False, False),
    ('application/vnd.oma.dd2+xml', False, False),
    ('application/vnd.oasis.opendocument.text-web', False, False),
    ('application/oebps-package+xml', False, False),
    ('application/vnd.intu.qbo', False, False),
    ('application/vnd.openofficeorg.extension', False, False),
    ('application/vnd.yamaha.openscoreformat', False, False),
    ('audio/webm', False, False),
    ('video/webm', False, False),
    ('application/vnd.oasis.opendocument.chart', False, False),
    ('application/vnd.oasis.opendocument.chart-template', False, False),
    ('application/vnd.oasis.opendocument.database', False, False),
    ('application/vnd.oasis.opendocument.formula', False, False),
    ('application/vnd.oasis.opendocument.formula-template', False, False),
    ('application/vnd.oasis.opendocument.graphics', False, False),
    ('application/vnd.oasis.opendocument.graphics-template', False, False),
    ('application/vnd.oasis.opendocument.image', False, False),
    ('application/vnd.oasis.opendocument.image-template', False, False),
    ('application/vnd.oasis.opendocument.presentation', False, False),
    ('application/vnd.oasis.opendocument.presentation-template', False, False),
    ('application/vnd.oasis.opendocument.spreadsheet', False, False),
    ('application/vnd.oasis.opendocument.spreadsheet-template', False, False),
    ('application/vnd.oasis.opendocument.text', False, False),
    ('application/vnd.oasis.opendocument.text-master', False, False),
    ('application/vnd.oasis.opendocument.text-template', False, False),
    ('image/ktx', False, False),
    ('application/vnd.sun.xml.calc', False, False),
    ('application/vnd.sun.xml.calc.template', False, False),
    ('application/vnd.sun.xml.draw', False, False),
    ('application/vnd.sun.xml.draw.template', False, False),
    ('application/vnd.sun.xml.impress', False, False),
    ('application/vnd.sun.xml.impress.template', False, False),
    ('application/vnd.sun.xml.math', False, False),
    ('application/vnd.sun.xml.writer', False, False),
    ('application/vnd.sun.xml.writer.global', False, False),
    ('application/vnd.sun.xml.writer.template', False, False),
    ('application/x-font-otf', False, False),
    ('application/vnd.yamaha.openscoreformat.osfpvg+xml', False, False),
    ('application/vnd.osgi.dp', False, False),
    ('application/vnd.palm', False, False),
    ('text/x-pascal', False, False),
    ('application/vnd.pawaafile', False, False),
    ('application/vnd.hp-pclxl', False, False),
    ('application/vnd.picsel', False, False),
    ('image/x-pcx', False, False),
    ('image/vnd.adobe.photoshop', False, False),
    ('application/pics-rules', False, False),
    ('image/x-pict', False, False),
    ('application/x-chat', False, False),
    ('application/pkcs10', False, False),
    ('application/x-pkcs12', False, False),
    ('application/pkcs7-mime', False, False),
    ('application/pkcs7-signature', False, False),
    ('application/x-pkcs7-certreqresp', False, False),
    ('application/x-pkcs7-certificates', False, False),
    ('application/pkcs8', False, False),
    ('application/vnd.pocketlearn', False, False),
    ('image/x-portable-anymap', False, False),
    ('image/x-portable-bitmap', False, False),
    ('application/x-font-pcf', False, False),
    ('application/font-tdpfr', False, False),
    ('application/x-chess-pgn', False, False),
    ('image/x-portable-graymap', False, False),
    ('image/png', False, False),
    ('image/x-citrix-png', False, False),
    ('image/x-png', False, False),
    ('image/x-portable-pixmap', False, False),
    ('application/pskc+xml', False, False),
    ('application/vnd.ctc-posml', False, False),
    ('application/postscript', False, False),
    ('application/x-font-type1', False, False),
    ('application/vnd.powerbuilder6', False, False),
    ('application/pgp-encrypted', False, False),
    ('application/pgp-signature', False, False),
    ('application/vnd.previewsystems.box', False, False),
    ('application/vnd.pvi.ptid1', False, False),
    ('application/pls+xml', False, False),
    ('application/vnd.pg.format', False, False),
    ('application/vnd.pg.osasli', False, False),
    ('text/prs.lines.tag', False, False),
    ('application/x-font-linux-psf', False, False),
    ('application/vnd.publishare-delta-tree', False, False),
    ('application/vnd.pmi.widget', False, False),
    ('application/vnd.quark.quarkxpress', False, False),
    ('application/vnd.epson.esf', False, False),
    ('application/vnd.epson.msf', False, False),
    ('application/vnd.epson.ssf', False, False),
    ('application/vnd.epson.quickanime', False, False),
    ('application/vnd.intu.qfx', False, False),
    ('video/quicktime', False, False),
    ('application/x-rar-compressed', False, False),
    ('audio/x-pn-realaudio', False, False),
    ('audio/x-pn-realaudio-plugin', False, False),
    ('application/rsd+xml', False, False),
    ('application/vnd.rn-realmedia', False, False),
    ('application/vnd.realvnc.bed', False, False),
    ('application/vnd.recordare.musicxml', False, False),
    ('application/vnd.recordare.musicxml+xml', False, False),
    ('application/relax-ng-compact-syntax', False, False),
    ('application/vnd.data-vision.rdz', False, False),
    ('application/rdf+xml', False, False),
    ('application/vnd.cloanto.rp9', False, False),
    ('application/vnd.jisp', False, False),
    ('application/rtf', False, False),
    ('text/richtext', False, False),
    ('application/vnd.route66.link66+xml', False, False),
    ('application/rss+xml', False, False),
    ('application/shf+xml', False, False),
    ('application/vnd.sailingtracker.track', False, False),
    ('image/svg+xml', False, False),
    ('application/vnd.sus-calendar', False, False),
    ('application/sru+xml', False, False),
    ('application/set-payment-initiation', False, False),
    ('application/set-registration-initiation', False, False),
    ('application/vnd.sema', False, False),
    ('application/vnd.semd', False, False),
    ('application/vnd.semf', False, False),
    ('application/vnd.seemail', False, False),
    ('application/x-font-snf', False, False),
    ('application/scvp-vp-request', False, False),
    ('application/scvp-vp-response', False, False),
    ('application/scvp-cv-request', False, False),
    ('application/scvp-cv-response', False, False),
    ('application/sdp', False, False),
    ('text/x-setext', False, False),
    ('video/x-sgi-movie', False, False),
    ('application/vnd.shana.informed.formdata', False, False),
    ('application/vnd.shana.informed.formtemplate', False, False),
    ('application/vnd.shana.informed.interchange', False, False),
    ('application/vnd.shana.informed.package', False, False),
    ('application/thraud+xml', False, False),
    ('application/x-shar', False, False),
    ('image/x-rgb', False, False),
    ('application/vnd.epson.salt', False, False),
    ('application/vnd.accpac.simply.aso', False, False),
    ('application/vnd.accpac.simply.imp', False, False),
    ('application/vnd.simtech-mindmapper', False, False),
    ('application/vnd.commonspace', False, False),
    ('application/vnd.yamaha.smaf-audio', False, False),
    ('application/vnd.smaf', False, False),
    ('application/vnd.yamaha.smaf-phrase', False, False),
    ('application/vnd.smart.teacher', False, False),
    ('application/vnd.svd', False, False),
    ('application/sparql-query', False, False),
    ('application/sparql-results+xml', False, False),
    ('application/srgs', False, False),
    ('application/srgs+xml', False, False),
    ('application/ssml+xml', False, False),
    ('application/vnd.koan', False, False),
    ('text/sgml', False, False),
    ('application/vnd.stardivision.calc', False, False),
    ('application/vnd.stardivision.draw', False, False),
    ('application/vnd.stardivision.impress', False, False),
    ('application/vnd.stardivision.math', False, False),
    ('application/vnd.stardivision.writer', False, False),
    ('application/vnd.stardivision.writer-global', False, False),
    ('application/vnd.stepmania.stepchart', False, False),
    ('application/x-stuffit', False, False),
    ('application/x-stuffitx', False, False),
    ('application/vnd.solent.sdkm+xml', False, False),
    ('application/vnd.olpc-sugar', False, False),
    ('audio/basic', False, False),
    ('application/vnd.wqd', False, False),
    ('application/vnd.symbian.install', False, False),
    ('application/smil+xml', False, False),
    ('application/vnd.syncml+xml', False, False),
    ('application/vnd.syncml.dm+wbxml', False, False),
    ('application/vnd.syncml.dm+xml', False, False),
    ('application/x-sv4cpio', False, False),
    ('application/x-sv4crc', False, False),
    ('application/sbml+xml', False, False),
    ('text/tab-separated-values', False, False),
    ('image/tiff', False, False),
    ('application/vnd.tao.intent-module-archive', False, False),
    ('application/x-tar', False, False),
    ('application/x-tcl', False, False),
    ('application/x-tex', False, False),
    ('application/x-tex-tfm', False, False),
    ('application/tei+xml', False, False),
    ('text/plain', False, False),
    ('application/vnd.spotfire.dxp', False, False),
    ('application/vnd.spotfire.sfs', False, False),
    ('application/timestamped-data', False, False),
    ('application/vnd.trid.tpt', False, False),
    ('application/vnd.triscape.mxs', False, False),
    ('text/troff', False, False),
    ('application/vnd.trueapp', False, False),
    ('application/x-font-ttf', False, False),
    ('text/turtle', False, False),
    ('application/vnd.umajin', False, False),
    ('application/vnd.uoml+xml', False, False),
    ('application/vnd.unity', False, False),
    ('application/vnd.ufdl', False, False),
    ('text/uri-list', False, False),
    ('application/vnd.uiq.theme', False, False),
    ('application/x-ustar', False, False),
    ('text/x-uuencode', False, False),
    ('text/x-vcalendar', False, False),
    ('text/x-vcard', False, False),
    ('application/x-cdlink', False, False),
    ('application/vnd.vsf', False, False),
    ('model/vrml', False, False),
    ('application/vnd.vcx', False, False),
    ('model/vnd.mts', False, False),
    ('model/vnd.vtu', False, False),
    ('application/vnd.visionary', False, False),
    ('video/vnd.vivo', False, False),
    ('application/ccxml+xml', False, False),
    ('application/voicexml+xml', False, False),
    ('application/x-wais-source', False, False),
    ('application/vnd.wap.wbxml', False, False),
    ('image/vnd.wap.wbmp', False, False),
    ('audio/x-wav', False, False),
    ('application/davmount+xml', False, False),
    ('application/x-font-woff', False, False),
    ('application/wspolicy+xml', False, False),
    ('image/webp', False, False),
    ('application/vnd.webturbo', False, False),
    ('application/widget', False, False),
    ('application/winhlp', False, False),
    ('text/vnd.wap.wml', False, False),
    ('text/vnd.wap.wmlscript', False, False),
    ('application/vnd.wap.wmlscriptc', False, False),
    ('application/vnd.wordperfect', False, False),
    ('application/vnd.wt.stf', False, False),
    ('application/wsdl+xml', False, False),
    ('image/x-xbitmap', False, False),
    ('image/x-xpixmap', False, False),
    ('image/x-xwindowdump', False, False),
    ('application/x-x509-ca-cert', False, False),
    ('application/x-xfig', False, False),
    ('application/xhtml+xml', False, False),
    ('application/xml', False, False),
    ('application/xcap-diff+xml', False, False),
    ('application/xenc+xml', False, False),
    ('application/patch-ops-error+xml', False, False),
    ('application/resource-lists+xml', False, False),
    ('application/rls-services+xml', False, False),
    ('application/resource-lists-diff+xml', False, False),
    ('application/xslt+xml', False, False),
    ('application/xop+xml', False, False),
    ('application/x-xpinstall', False, False),
    ('application/xspf+xml', False, False),
    ('application/vnd.mozilla.xul+xml', False, False),
    ('chemical/x-xyz', False, False),
    ('text/yaml', False, False),
    ('application/yang', False, False),
    ('application/yin+xml', False, False),
    ('application/vnd.zul', False, False),
    ('application/zip', False, False),
    ('application/vnd.handheld-entertainment+xml', False, False),
    ('application/vnd.zzazz.deck+xml', False, False),
    ('application/vnd.adobe.air-application-installer-package+zip', False, False),
    ('application/vnd.adobe.xdp+xml', False, False),
    ('multipart', False, False),
    ('application/x-www-form-urlencoded', False, False),

    ('invalid expression', True, False),
])
def test_validate_mimetype(value, fails, allow_empty):
    if not fails:
        validated = validate_mimetype(value, allow_empty = allow_empty)
        if value:
            assert validated is not None
        else:
            assert validated is None
    else:
        with pytest.raises(ValueError):
            value = validate_mimetype(value, allow_empty = allow_empty)
